spring:
  profiles:
    active: local

  #DB정보
  datasource:
    url: jdbc:mysql://localhost:3306/fftl_03_RemakeBoard?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA 정보
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
